[package]
name = "mrr-data-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
meta-relational-reasoning = { git = "https://github.com/tao3k/meta-relational-reasoning.git", rev = "ffde2798a5246a61f4d6f0e66d7f05156e55e38f", default-features = false }
mrr-data-arrow = { path = "../crates/mrr-data-arrow" }

[[bin]]
name = "ipc_import"
path = "fuzz_targets/ipc_import.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
