//! Dependency-light `MRR Data` schema and physical profile identifiers.
#![forbid(unsafe_code)]

mod profile;
mod schema;
pub use schema::{
    ARROW_VALUE_SCHEMA, BACKEND_AUTHORITY_CHANGE_SCHEMA, BACKEND_AUTHORITY_COMPLETION_SCHEMA,
    BACKEND_AUTHORITY_KEY_SCHEMA, BACKEND_AUTHORITY_PROPOSAL_SCHEMA, BACKEND_AUTHORITY_SCHEMA,
    BACKEND_COMPLETION_SCHEMA, BACKEND_DELIVERY_SCHEMA, BACKEND_DUCKDB_SCHEMA,
    BACKEND_EXPECTATION_SCHEMA, BACKEND_KEY_SCHEMA, BACKEND_REVISION_SCHEMA, BACKEND_TURSO_SCHEMA,
    BACKEND_WRITE_SCHEMA, GRAPHAR_DATASET_BINDING_SCHEMA, GRAPHAR_DATASET_SCHEMA,
    GRAPHAR_ENTITY_PROPERTIES_SCHEMA, GRAPHAR_FILE_INVENTORY_SCHEMA, SchemaIdentity,
};

pub use profile::{
    ARROW_FACT_SCHEMA_NAMESPACE, ARROW_FACT_SCHEMA_VERSION, ARROW_IPC_FILE_FORMAT, CID_VERSION,
    DAG_CBOR_CODEC, DAG_CBOR_CODEC_NAME, GRAPHAR_BINARY_ENTITY_NAMESPACE,
    GRAPHAR_BINARY_ENTITY_VERSION, GRAPHAR_DATASET_NAMESPACE, GRAPHAR_ENTITY_PROPERTIES_NAMESPACE,
    GRAPHAR_ENTITY_PROPERTIES_VERSION, PROPERTY_SNAPSHOT_SCHEMA_VERSION, RAW_CODEC, RAW_CODEC_NAME,
    SHA2_256_CODE, SHA2_256_NAME, SNAPSHOT_SCHEMA_NAMESPACE, SNAPSHOT_SCHEMA_VERSION,
};

#[cfg(test)]
#[path = "../tests/unit/mod.rs"]
mod tests;
