[package]
name = "mrr-data-profile"
description = "Dependency-light schema and physical profile identifiers for MRR Data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
mrr-data-asp-rust-build-support.workspace = true

[lints]
workspace = true
